AWSTemplateFormatVersion: '2010-09-09'
Description: Monocyte Alarming Lambda
Parameters:
  bucketName:
    Description: aws-monocyte-alarming distrubtion bucket that contains the Lambda function zip file
    Type: String
  zipFile:
    Description: Name of the monocyte alarming distribution zip file inside the bucket
    Type: String
  config:
    Description: Config of the Monocyte Alarming
    Type: String
    Default: '{"sqs_queue":["queueName"],"sender_email":["sender-mail@domain.invalid"], "recipients":["recipients_mail@domain.invalid"], "dry_run":["True"], "USOFA_KEY":["usofa s3 key file"], "REGION_NAME":["aws region string"], "USOFA_BUCKET":["usofa s3 bucket name"]}'
Resources:
  monocyteUpdateRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Sid: ''
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - '*'
            Effect: Allow
            Resource:
            - '*'
          Version: '2012-10-17'
        PolicyName: monocyteUpdatePolicy
  monocyteAlarmingFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: bucketName
        S3Key:
          Ref: zipFile
      Description:
          Ref: config
      Handler: alarming_lambda.handler
      Role:
        Fn::GetAtt:
        - monocyteUpdateRole
        - Arn
      Runtime: python2.7
      Timeout: 15
