AWSTemplateFormatVersion: '2010-09-09'
Description: Monocyte Alarming Lambda
Outputs:
  lambdaFunctionName:
    Description: Name of the Monocyte Alarming Lambda function, to be used in separate API call to allow
      subscription to input SNS topic.
    Value:
      Ref: monocyteAlarmingFunction
Parameters:
  bucketName:
    Default: aws-monocyte-alarming
    Description: aws-monocyte-alarming distrubtion bucket that contains the Lambda function zip file
    Type: String
  zipFile:
    Description: Name of the monocyte alarming distribution zip file inside the bucket
    Type: String
    Default: latest/aws-monocyte-alarming-lambda.zip
Resources:
  monocyteUpdateRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Sid: ''
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - '*'
            Effect: Allow
            Resource:
            - '*'
          Version: '2012-10-17'
        PolicyName: monocyteUpdatePolicy
  monocyteAlarmingFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: bucketName
        S3Key:
          Ref: zipFile
      Description: lambda handler
      Handler: alarming_lambda.handler
      Role:
        Fn::GetAtt:
        - monocyteUpdateRole
        - Arn
      Runtime: python2.7
      Timeout: 15
